language: node_js
node_js:
  - "11"
  
env:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
      CLANG_VERSION="export CC=gcc-7 && export CXX=g++-7";
    fi
  #  - GCC_VERSION="export CC=gcc-6 && export CXX=g++-6"
  
os: 
  - linux
  - osx
  - windows

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      
osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
      wget https://www.saxonica.com/saxon-c/libsaxon-HEC-mac-setup-v1.2.0.zip -O /tmp/libsaxon-HEC-mac-setup-v1.2.0.zip;
      printf "y/n" | unzip /tmp/libsaxon-HEC-mac-setup-v1.2.0.zip -d /tmp/libsaxon-HEC-mac-setup-v1.2.0;
      mkdir -p `pwd`/../Saxonica/SaxonHEC1.2.0;
      cp -r -p /tmp/libsaxon-HEC-mac-setup-v1.2.0/* `pwd`/../Saxonica/SaxonHEC1.2.0;
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]] ; then
      wget http://www.saxonica.com/saxon-c/libsaxon-HEC-win-setup-v1.2.0.exe -O /tmp/libsaxon-HEC-win-setup-v1.2.0.exe;
      echo "installing saxon...";
      ls /tmp;
      C:/Users/travis/AppData/Local/Temp/libsaxon-HEC-win-setup-v1.2.0.exe /batch /dest /tmp/libsaxon-HEC-win-setup-v1.2.0;
      mkdir -p `pwd`/../Saxonica/SaxonHEC1.2.0;
      cp -r -p /tmp/ibsaxon-HEC-win-setup-v1.2.0/* `pwd`/../Saxonica/SaxonHEC1.2.0;
    else
      wget https://www.saxonica.com/saxon-c/libsaxon-HEC-setup64-v1.2.0.zip -O /tmp/libsaxon-HEC-setup64-v1.2.0.zip;
      printf "y/n" | unzip /tmp/libsaxon-HEC-setup64-v1.2.0.zip -d /tmp;
      printf "`pwd`/../Saxonica/SaxonHEC1.2.0\n" | /tmp/libsaxon-HEC-setup64-v1.2.0 ;
    fi
  - export SAXONC_HOME=`pwd`/../Saxonica/SaxonHEC1.2.0
  
install:
  - export SAXONC_HOME=`pwd`/../Saxonica/SaxonHEC1.2.0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
      ls /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/*;
      find /Library/Java/JavaVirtualMachines -name jni.h;
      export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home;
    fi
  - npm install -g node-gyp
  - npm install --build-from-source --saxonc_home=../Saxonica/SaxonHEC1.2.0

before-scripte:
  - export PATH=`pwd`/node_modules/.bin:${PATH}
  
script:
  - export PATH=`pwd`/node_modules/.bin:${PATH}
  - export NODE_PATH=`pwd`/build/Release:$NODE_PATH
  - export LD_LIBRARY_PATH=`pwd`/../Saxonica/SaxonHEC1.2.0:${LD_LIBRARY_PATH}
  - export DYLD_LIBRARY_PATH=`pwd`/../Saxonica/SaxonHEC1.2.0:${DYLD_LIBRARY_PATH}
  - ls `pwd`/../Saxonica
  - echo ${PATH}
  - ls `pwd`/node_modules/.bin
  - mocha --harmony --require should --timeout 7000
