language: node_js
node_js:
  - "node"
  - "9"
  - "8"
  - "6"
  
env:
  - GCC_VERSION="export CC=gcc-7 && export CXX=g++-7"
  #  - GCC_VERSION="export CC=gcc-6 && export CXX=g++-6"
  
os: 
  - linux
  - osx
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      
osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then
      wget http://www.saxonica.com/saxon-c/libsaxon-HEC-mac-setup-v1.1.0.zip -O /tmp/libsaxon-HEC-mac-setup-v1.1.0.zip;
      unzip /tmp/libsaxon-HEC-mac-setup-v1.1.0.zip -d `pwd`/Saxonica;
    else
      wget http://www.saxonica.com/saxon-c/libsaxon-HEC-setup64-v1.1.0.zip -O /tmp/libsaxon-HEC-setup64-v1.1.0.zip;
      unzip /tmp/libsaxon-HEC-setup64-v1.1.0.zip -d `pwd`/Saxonica;
    fi
  - export SAXONC_HOME=`pwd`/Saxonica/Saxon-HEC1.1.0
  
install:
  - export SAXONC_HOME=`pwd`/Saxonica/Saxon-HEC1.1.0
  - npm install --build-from-source

before-scripte:
  - export PATH=`pwd`/node_modules/.bin:${PATH}
  
script:
  - export PATH=`pwd`/node_modules/.bin:${PATH}
  - export LD_LIBRARY_PATH=`pwd`/Saxonica/Saxon-HEC1.1.0:${LD_LIBRARY_PATH}
  - export DYLD_LIBRARY_PATH=`pwd`/Saxonica/Saxon-HEC1.1.0:${DYLD_LIBRARY_PATH}
  - echo ${PATH}
  - ls `pwd`/node_modules/.bin
  - mocha --harmony --require should --require co-mocha --timeout 7000
